set nocompatible

" show line numbers
set number

" Set syntax highlighting to always on
syntax enable

" Set automatic filetype detection to on
filetype plugin indent on

" Colorscheme
set background=dark
colorscheme solarized " default colorcheme
"colorscheme zenburn
"set background=dark
"colorscheme solarized
"colorscheme vividchalk

if has('autocmd')
	autocmd WinEnter,FileType sh,c,h colorscheme vividchalk
	autocmd WinEnter,FileType * colorscheme solarized
endif

" Disable VIM swap and backup files
set nobackup
set nowritebackup
set noswapfile

" Set fonts
if has('gui_running')
	set guioptions-=m  "remove menu bar
	set guioptions-=T  "remove toolbar
	set guioptions-=r  "remove right-hand scroll bar
	
	if has('gui_win32')
		set guifont=Consolas:h10:cANSI
	elseif has('gui_gtk')
		"set guifont=Inconsolata\ 12
		set guifont=Droid\ Sans\ Mono\ 12
		"set guifont=DejaVu\ Sans\ Mono\ 12
	endif

	"vertical line
	set colorcolumn=80
endif

" paste from system cilpbord
set clipboard=unnamed

" encoding
"set filenc=utf8
set encoding=utf8

set showtabline=4
set softtabstop=4
set tabstop=4
set shiftwidth=4

vmap <Tab> >gv
vmap <S-Tab> <gv

" map tabnext, tabprevious and tabnew (like firefox)
map <C-tab> :tabnext<CR>
map <C-S-tab> :tabprevious<CR>
nmap <C-t> :tabnew<CR>i
imap <C-t> <ESC>:tabnew<CR>i

